/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class shulaing_han_ndk_callback_DataProvider */

#ifndef _Included_shulaing_han_ndk_callback_DataProvider
#define _Included_shulaing_han_ndk_callback_DataProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     shulaing_han_ndk_callback_DataProvider
 * Method:    callCcode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_shulaing_han_ndk_1callback_DataProvider_callCcode
  (JNIEnv *, jobject);

/*
 * Class:     shulaing_han_ndk_callback_DataProvider
 * Method:    callCcode1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_shulaing_han_ndk_1callback_DataProvider_callCcode1
  (JNIEnv *, jobject);

/*
 * Class:     shulaing_han_ndk_callback_DataProvider
 * Method:    callCcode2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_shulaing_han_ndk_1callback_DataProvider_callCcode2
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
